Wrapped2340/games/urls.py
from django.urls import path

from . import views

app_name = "games"

urlpatterns = [
    path("whats-the-buzz", views.WhatsTheBuzzView.as_view(), name="whats-the-buzz"),
    path("gta", views.GtaView.as_view(), name="gta"),
    path("", views.HomeView.as_view(), name="home"),
]

Wrapped2340/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='home:home-redirect'), name='home-redirect'),
    path('admin/', admin.site.urls),
    path('users/', include('Wrapped2340.users.urls')),
    path('home/', include('Wrapped2340.home.urls')),

    path('slides/', include('Wrapped2340.slides.urls')),
    path('games/', include('Wrapped2340.games.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Wrapped2340/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.WrappedLoginView.as_view(), name="login"),
    path("logout/", views.WrappedLogoutView.as_view(), name="logout"),
    path("account-settings/", views.AccountSettingsView.as_view(), name="account-settings"),
    path("change-password/", views.WrappedPasswordChangeView.as_view(), name="password-change"),
    path("reset-password/", views.WrappedPasswordResetView.as_view(), name="password-reset"),
    path("reset-password-done/", views.WrappedPasswordResetDoneView.as_view(), name="password-reset-done"),
    path("reset-password-confirm/<uidb64>/<token>/", views.WrappedPasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("reset-password-complete/", views.WrappedPasswordResetCompleteView.as_view(), name="password-reset-complete"),
    path('link-spotify/', views.LinkSpotify.as_view(), name='link-spotify'),
    path('rotate-invite-token/', views.RotateInviteTokenView.as_view(), name='rotate-invite-token'),
    path('delete-account/', views.DeleteAccountView.as_view(), name='delete-account'),
    path('dev-feedback/', views.submit_feedback, name='dev-feedback'),
    path('manage-feedback/', views.manage_feedback, name='manage-feedback'),
]

Wrapped2340/common/models.py
from django.db import models
from Wrapped2340.users.models import UserProfile

class Wrapped(models.Model):
    version = models.CharField(max_length=20)
    creator1 = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='creator1')
    creator2 = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='creator2', null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=False)
    caption = models.CharField(max_length=100, blank=True)
    content = models.JSONField(default=dict)

    def default_content(self):
        if self.creator2:
            return self.content['duo1']
        else:
            return self.content

    def __str__(self):
        noun = "Public wrapped" if self.public else "Wrapped"
        time = "Created at %s" % self.time_created
        created_by = (("By %s and %s" % (self.creator1.user.username, self.creator2.user.username))
                      if self.creator2 else
                      ("By %s" % self.creator1))
        caption_text = ("Caption: \"%s\"" % self.caption) if self.caption else "No caption"
        return "%s\n%s\n%s\n%s" % (noun, created_by, time, caption_text)


class CommonFeedback(models.Model):
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    resolved = models.BooleanField(default=False)

    def __str__(self):
        return f"Feedback: {self.message[:20]}"

class PreviewUrl(models.Model):
    name = models.CharField(max_length=255)
    artist = models.CharField(max_length=255, null=True)
    url = models.TextField()

    def __str__(self):
        return f"Name: {self.name}"

Wrapped2340/common/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Wrapped Up{% endblock %}</title>
        <link href="{% static 'css/output.css' %}" rel="stylesheet" type="text/css">
        <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet" type="text/css">
        <script src="https://cdn.jsdelivr.net/npm/theme-change@2.0.2/index.js"></script>
        {% block head %}{% endblock %}
    </head>
    <body class="bg-base-200 flex flex-col max-h-dvh" style="font-family: 'Poppins', sans-serif;">
        <div class="navbar bg-base-200 shadow-lg">
            <div class="flex-1">
                <a href="{% url 'home:home-redirect' %}" class="btn btn-ghost normal-case text-xl">AudioScape</a>
                <div class="dropdown flex-nowrap">
                    <div  class="btn m-1 bg-base-300" tabindex="0" role="button">
                        Theme
                        <svg
                                width="12px"
                                height="12px"
                                class="inline-block h-2 w-2 fill-current opacity-60"
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 2048 2048">
                            <path d="M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z"></path>
                        </svg>
                    </div >
                    <ul tabindex="0" class="dropdown-content z-[1] flex flex-col flex-nowrap menu basis-2/4 bg-base-300 rounded-box max-h-80 overflow-y-scroll shadow" style="scrollbar-width: none; -ms-overflow-style: none;">
                        <li><button data-set-theme="light" data-act-class="active">Light</button></li>
                        <li><button data-set-theme="dark" data-act-class="active">Dark</button></li>
                        <li><button data-set-theme="cupcake" data-act-class="active">Cupcake</button></li>
                        <li><button data-set-theme="bumblebee" data-act-class="active">Bumblebee</button></li>
                        <li><button data-set-theme="emerald" data-act-class="active">Emerald</button></li>
                        <li><button data-set-theme="corporate" data-act-class="active">Corporate</button></li>
                        <li><button data-set-theme="synthwave" data-act-class="active">Synthwave</button></li>
                        <li><button data-set-theme="retro" data-act-class="active">Retro</button></li>
                        <li><button data-set-theme="cyberpunk" data-act-class="active">Cyberpunk</button></li>
                        <li><button data-set-theme="valentine" data-act-class="active">Valentine</button></li>
                        <li><button data-set-theme="halloween" data-act-class="active">Halloween</button></li>
                        <li><button data-set-theme="garden" data-act-class="active">Garden</button></li>
                        <li><button data-set-theme="forest" data-act-class="active">Forest</button></li>
                        <li><button data-set-theme="aqua" data-act-class="active">Aqua</button></li>
                        <li><button data-set-theme="lofi" data-act-class="active">Lo-fi</button></li>
                        <li><button data-set-theme="pastel" data-act-class="active">Pastel</button></li>
                        <li><button data-set-theme="fantasy" data-act-class="active">Fantasy</button></li>
                        <li><button data-set-theme="wireframe" data-act-class="active">Wireframe</button></li>
                        <li><button data-set-theme="black" data-act-class="active">Black</button></li>
                        <li><button data-set-theme="luxury" data-act-class="active">Luxury</button></li>
                        <li><button data-set-theme="dracula" data-act-class="active">Dracula</button></li>
                        <li><button data-set-theme="cmyk" data-act-class="active">CMYK</button></li>
                        <li><button data-set-theme="autumn" data-act-class="active">Autumn</button></li>
                        <li><button data-set-theme="business" data-act-class="active">Business</button></li>
                        <li><button data-set-theme="acid" data-act-class="active">Acid</button></li>
                        <li><button data-set-theme="lemonade" data-act-class="active">Lemonade</button></li>
                        <li><button data-set-theme="night" data-act-class="active">Night</button></li>
                        <li><button data-set-theme="coffee" data-act-class="active">Coffee</button></li>
                        <li><button data-set-theme="winter" data-act-class="active">Winter</button></li>
                        <li><button data-set-theme="dim" data-act-class="active">Dim</button></li>
                        <li><button data-set-theme="nord" data-act-class="active">Nord</button></li>
                        <li><button data-set-theme="sunset" data-act-class="active">Sunset</button></li>
                    </ul>
                </div>

                <div class="hidden md:flex space-x-4">
                    <a href="{% url 'home:discover' %}" class="btn btn-ghost text-xl">Discover</a>
                    <a href="{% url 'home:home' %}" class="btn btn-ghost text-xl">My Wraps</a>
                    <a href="{% url 'games:home' %}" class="btn btn-ghost text-xl">Games</a>
                </div>

            </div>
            <div class="flex-none">
                <div class="flex-none">
                    {% if user.is_authenticated %}
                        <a href="{% url 'home:home' %}">
                            Hello <span class="font-bold">{{ user.username }}</span>!
                        </a>
                    {% else %}
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Log In/Register</a>
                    {% endif %}
                </div>

                <div class="dropdown dropdown-end">
                    <div tabindex="0" role="button" class="btn btn-square btn-ghost">
                        <svg
                                xmlns="http://www.w3.org/2000/svg"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke-width="2"
                                stroke="currentColor"
                                class="inline-block h-6 w-6 stroke-current">
                            <path
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    d="M4 6h16M4 12h16M4 18h16"></path>
                        </svg>
                    </div>
                    <ul tabindex="0" class="dropdown-content menu bg-base-300 rounded-box z-[1] w-52 p-2 shadow">
                        <!-- Users-related links -->
                        <li class="md:hidden"><a class="md:hidden" href="{% url 'home:discover' %}">Discover</a></li>
                        <li class="md:hidden"><a class="md:hidden" href="{% url 'home:home' %}">My Wraps</a></li>
                        <li class="md:hidden"><a class="md:hidden" href="{% url 'games:home' %}">Games</a></li>
                        <li><a href="{% url 'users:account-settings' %}">Account Settings</a></li>
                        <li><a href="{% url 'users:dev-feedback' %}">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container mx-auto p-6 overflow-y-auto h-dvh" style="scrollbar-width: none; -ms-overflow-style: none;">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>