Wrapped2340/games/urls.py
from django.urls import path

from . import views

app_name = "games"

urlpatterns = [
    path("whats-the-buzz", views.WhatsTheBuzzView.as_view(), name="whats-the-buzz"),
    path("gta", views.GtaView.as_view(), name="gta"),
    path("", views.HomeView.as_view(), name="home"),
]

Wrapped2340/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='home:home-redirect'), name='home-redirect'),
    path('admin/', admin.site.urls),
    path('users/', include('Wrapped2340.users.urls')),
    path('home/', include('Wrapped2340.home.urls')),

    path('slides/', include('Wrapped2340.slides.urls')),
    path('games/', include('Wrapped2340.games.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Wrapped2340/games/forms.py
from django.forms import forms, CharField, HiddenInput


class WhatsTheBuzzForm(forms.Form):
    chosen_artist = CharField(widget=HiddenInput())
    correct_hash = CharField(widget=HiddenInput())

Wrapped2340/games/views.py
import base64
import os
import random
import itertools
from datetime import datetime
import re
import hashlib

import requests
from django.shortcuts import redirect
from django.views.generic import TemplateView, FormView
from Wrapped2340.common import spotifyAPI
from Wrapped2340 import settings
from Wrapped2340.common.spotifyAPI import get_albums
from Wrapped2340.games import forms
from Wrapped2340.settings import reddit


class WhatsTheBuzzView(FormView):
    form_class = forms.WhatsTheBuzzForm
    template_name = 'games/whats-the-buzz/game.html'

    def form_valid(self, form):
        chosen_artist = form.cleaned_data['chosen_artist']
        correct_hash = form.cleaned_data['correct_hash']
        chosen_hash = get_artist_hash(chosen_artist, self.request.user.userprofile)
        if chosen_hash == correct_hash:
            return redirect('games:whats-the-buzz-correct')
        else:
            return redirect('games:whats-the-buzz-incorrect')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        userprofile = self.request.user.userprofile
        random.seed(datetime.now().microsecond)
        top_artists = spotifyAPI.get_top_artists(userprofile, limit=20, timeframe='medium_term')
        for i in range(10):
            artist = random.choice(top_artists)
            try:
                real_post_choices = search_reddit(get_search_term(artist), limit=7)
                real_post = random.choice(real_post_choices)

                post_text = real_post.selftext[:400]
                context['reveal_text'] = post_text

                post_text = redact_with_artist(post_text, artist, userprofile).replace('\n', '<br>')

                post_title = real_post.title
                context['reveal_title'] = post_title
                post_title = redact_with_artist(post_title, artist, userprofile)

                if post_title == '':
                    continue
                context['post_title'] = post_title
                context['post_text'] = post_text

                choices = get_incorrect_choices(artist, top_artists, userprofile)
                correct_index = random.randrange(3)
                choices.insert(correct_index, artist)
                context['choices'] = [c['name'] for c in choices]
                context['correct'] = artist

                context['success'] = True
                return context
            except Exception as e:
                print(e)
                continue
        context['success'] = False
        return context

def get_search_term(artist):
    return 'self:true title:"%s" (artist OR band OR album OR song OR topster OR rym) NOT sale' % (artist['name'])

def get_incorrect_choices(artist, top_artists, userprofile):
    related = top_artists
    related = related[:3]
    other_top_artists = list(filter(lambda a: a != artist and artist not in related, top_artists))
    related[random.randrange(3)] = random.choice(other_top_artists)
    return related

def search_reddit(query, limit):
    listings = settings.reddit.subreddit('all').search(query, limit=limit)
    return list(listings)

def redact(text, term):
    new_text = text
    regex = re.compile(r'\b%s\b' % re.escape(term), re.IGNORECASE)
    new_text = regex.sub(r'<span class="highlight">[...]</span>', new_text)
    return new_text

allowed_words = ['the', 'a', 'an', 'of', 'my', 'I', 'you', 'your', 'in', 'is', 'back', 'if', 'to', 'remastered']

def redact_with_artist(text, artist, userprofile):
    new_text = text

    albums = spotifyAPI.get_albums(artist['id'], userprofile)
    for album in albums:
        album_title = album['name']
        new_text = redact(new_text, album_title)
        for word in album_title.split(' '):
            if word[0].isupper() and word.lower() not in allowed_words:
                new_text = redact(new_text, word)
    artist_name = artist['name']
    new_text = redact(new_text, artist_name)
    for word in artist_name.split(' '):
        if word.lower() not in allowed_words:
            new_text = redact(new_text, word)

    return new_text

class GtaView(TemplateView):
    template_name = 'games/gta/game.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        userprofile = self.request.user.userprofile
        random.seed(datetime.now().microsecond)
        top_artists = spotifyAPI.get_top_artists(userprofile, limit=30, timeframe='medium_term')
        artist = random.choice(top_artists)

        top_tracks = spotifyAPI.get_top_artist_tracks(artist['id'], userprofile)[:5]
        acronyms = [acronym(track['name']) for track in top_tracks]

        context['acronyms'] = acronyms
        context['songs'] = [track['name'] for track in top_tracks]
        context['artist'] = artist['name']
        context['success'] = True
        return context

def acronym(track_name):
    words = track_name.split(' ')
    result = ''
    for word in words:
        for i, c in enumerate(word):
            if c == '(':
                result += c
            if c.isalnum():
                result += c
                for c in word[i+1:]:
                    if c == ')':
                        result += c
                break
        else:
            if len(word) == 1:
                result += ' %s ' % word
    return result

class HomeView(TemplateView):
    template_name = 'games/home.html'

Wrapped2340/games/templates/games/gta/game.html
{% extends 'games/base.html' %}

{% block game_head %}
    <script>
const artist = '{{ artist|safe }}'
const acronyms = {{ acronyms|safe }}
const songs = {{ songs|safe }}
let guesses = []
let guessNum = 0

window.onload = start

function start() {
    let first_acronym = document.getElementById('acronym0')
    first_acronym.innerText = acronyms[0]
    let inputForm = document.getElementById('input-form')
    inputForm.addEventListener('submit', guess)
}

function process(name) {
    return name
        .toLowerCase()
        .replaceAll(/[,.-]/g, '')
        .replaceAll('&', 'and')
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
}

function guess(event, skip) {
    event.preventDefault()
    let inputElement = document.getElementById('input')
    let rawInput = inputElement.value
    let input = process(rawInput)

    if (input === process(artist)) {
        if (guessNum === 0) {
            revealAnswer(`You got it on the first guess! Outstanding!`, true)
        } else {
            revealAnswer(`You got it in ${guessNum + 1} guesses!`, true)
        }
        return
    }

    if (guesses.includes(input) && input !== '') {
        return
    }

    guesses.push(input.toLowerCase())

    guessNum += 1
    if (guessNum >= 5) {
        revealAnswer('Sorry, you ran out of guesses.', false)
    } else {
        let nextAcronym = document.getElementById('acronym' + guessNum)
        nextAcronym.innerText = acronyms[guessNum]
    }
}

function revealAnswer(message, alert) {
    for (let i = 0; i < 5; i++) {
        let nextAcronym = document.getElementById('acronym' + i)
        nextAcronym.innerText = songs[i]
    }
    let answer = document.getElementById('answer')
    answer.innerText = `The answer was ${artist}!`
    let status = document.getElementById('status')
    status.innerText = message
    let alertElem = document.getElementById('alert')
    if (alert) {
        alertElem.className = "alert alert-success"
    } else {
        alertElem.className = "alert alert-error"
    }
    let tryAgain = document.getElementById('try-again')
    tryAgain.innerText = 'Try again?'
    tryAgain.className = "btn btn-secondary m-2"
    let inputForm = document.getElementById('input-form')
    inputForm.hidden = true
}
    </script>
{% endblock %}

{% block content %}
    <h1 class="text-2xl md:text-5xl font-bold m-2">
        G.T.A.: Guess That Artist
        <div class="dropdown dropdown-end">
            <div tabindex="0" role="button" class="btn btn-ghost btn-xs text-info">
                How To?
            </div>
            <div
                    tabindex="0"
                    class="card compact dropdown-content bg-base-100 rounded-box z-[1] w-40 md:w-80 shadow">
                <div tabindex="0" class="card-body">
                    You get 5 acronyms for an artist's top 5 songs, and you have 5 chances to guess the artist.
                </div>
            </div>
        </div>
    </h1>
    <div class="card bg-base-100 w-3/4 shadow-xl justify-self-center m-2">
        <div class="card-body text-center">
            {% for acronym in acronyms %}
                <h2 class="text-xl md:text-4xl font-bold m-2" id="acronym{{ forloop.counter0 }}"></h2>
            {% endfor %}
        </div>
    </div>

    <form id="input-form">
        <input class="input" type="text" id="input" autocomplete="off" placeholder="Input your guess...">
        <button class="btn btn-primary">Guess</button>
    </form>
    <div id="alert">
        <h1 id="status"></h1>
        <h1 id="answer"></h1>
    </div>
    <h2 id="answer"></h2>
    <p>
        <a href="{% url 'games:gta' %}" id="try-again"></a>
    </p>
{% endblock %}